- name: Redis setup
  hosts: all
  become: yes
  tasks:
    - name : Install Redis repo
      ansible.builtin.yum:
        name: yum install https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: installed

    - name: Enable redis module
      ansible.builtin.shell: yum module enable redis:remi-6.2

    - name: Install redis
      ansible.builtin.yum:
        - name: yum install redis -y
          state: started

    - name: update Listen Address /etc/redis.conf
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: update Listen Address /etc/redis/redis.conf
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start Redis
      ansible.builtin.systemd:
        name: redis
        state: started
        enabled: yes







